// Nepali uses Devanagari script, similar to Hindi but can have slight variations in pronunciation/usage.
// For simplicity in this context, we'll reuse the Hindi set mostly but defined separately for flexibility.

Map<String, String> nepaliSounds = {
  'अ': 'a',
  'आ': 'aa',
  'इ': 'i',
  'ई': 'ee',
  'उ': 'u',
  'ऊ': 'oo',
  'ऋ': 'ri',
  'ए': 'e',
  'ऐ': 'ai',
  'ओ': 'o',
  'औ': 'au',
  'क': 'ka',
  'ख': 'kha',
  'ग': 'ga',
  'घ': 'gha',
  'ङ': 'nga',
  'च': 'cha',
  'छ': 'chha',
  'ज': 'ja',
  'झ': 'jha',
  'ञ': 'nya',
  'ट': 'ta',
  'ठ': 'tha',
  'ड': 'da',
  'ढ': 'dha',
  'ण': 'na',
  'त': 'ta',
  'थ': 'tha',
  'द': 'da',
  'ध': 'dha',
  'न': 'na',
  'प': 'pa',
  'फ': 'pha',
  'ब': 'ba',
  'भ': 'bha',
  'म': 'ma',
  'य': 'ya',
  'र': 'ra',
  'ल': 'la',
  'व': 'va',
  'श': 'sha',
  'ष': 'sha',
  'स': 'sa',
  'ह': 'ha',
  'क्ष': 'ksha',
  'त्र': 'tra',
  'ज्ञ': 'gya'
};

Map<String, String> nepaliVowels = {
  'अ': 'a',
  'आ': 'aa',
  'इ': 'i',
  'ई': 'ee',
  'उ': 'u',
  'ऊ': 'oo',
  'ऋ': 'ri',
  'ए': 'e',
  'ऐ': 'ai',
  'ओ': 'o',
  'औ': 'au',
  'अं': 'am',
  'अः': 'ah'
};

Map<String, String> nepaliConsonants = {
  'क': 'ka',
  'ख': 'kha',
  'ग': 'ga',
  'घ': 'gha',
  'ङ': 'nga',
  'च': 'cha',
  'छ': 'chha',
  'ज': 'ja',
  'झ': 'jha',
  'ञ': 'nya',
  'ट': 'ta',
  'ठ': 'tha',
  'ड': 'da',
  'ढ': 'dha',
  'ण': 'na',
  'त': 'ta',
  'थ': 'tha',
  'द': 'da',
  'ध': 'dha',
  'न': 'na',
  'प': 'pa',
  'फ': 'pha',
  'ब': 'ba',
  'भ': 'bha',
  'म': 'ma',
  'य': 'ya',
  'र': 'ra',
  'ल': 'la',
  'व': 'va',
  'श': 'sha',
  'ष': 'sha',
  'स': 'sa',
  'ह': 'ha',
  'क्ष': 'ksha',
  'त्र': 'tra',
  'ज्ञ': 'gya'
};
